name: mlflow-demo-iris-ci
on:
  push:
    branches:
      - master
#  pull_request:
#    types: [opened, reopened]
#    branches:
#      - master
permissions:
  id-token: write
  contents: read
env:
  AWS_REGION: us-east-1
  APPLICATION: mlflow-demo-iris
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::127923327338:role/github-actions-mlflow
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com
      - name: ECR login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3
#      - name: Docker build/push Training image
#        uses: docker/build-push-action@v5
#        env:
#          DOCKER_IMAGE: "${{ steps.login-ecr.outputs.registry }}/${{ env.APPLICATION }}-base:latest"
#        with:
#          context: mlflow/
#          push: true
#          tags: ${{ env.DOCKER_IMAGE }}
      - name: Config kubeconfig
        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name eks-infra --kubeconfig ${{ github.workspace }}/contexts
      - name: aaa
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 127923327338.dkr.ecr.us-east-1.amazonaws.com
      - name: Run training
        env:
          DOCKER_IMAGE: "${{ steps.login-ecr.outputs.registry }}/${{ env.APPLICATION }}-base:latest"
          MLFLOW_EXPERIMENT_NAME: iris
          MLFLOW_TRACKING_URI: 'https://mlflow.ricardoxyz.website'
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        #run: docker run --rm ${{ env.DOCKER_IMAGE }} mlflow run /mlflow/projects/code/ --backend kubernetes --backend-config /mlflow/projects/code/kubernetes_backend.json 
        run: docker build --tag ${{ env.DOCKER_IMAGE }} mlflow/ && docker run --rm --volume /var/run/docker.sock:/var/run/docker.sock --volume /home/runner/.docker/config.json:/root/.docker/config.json --volume ${{ github.workspace }}/contexts:/root/.kube/contexts ${{ env.DOCKER_IMAGE }} mlflow run /mlflow/projects/code/ --backend kubernetes --backend-config /mlflow/projects/code/kubernetes_backend.json 
        shell: bash
